### PR TITLE
feat:three dots feature completed

### PR DESCRIPTION
**Pull request by shashikantmaurya0007**
feature:three in video cards and its respective feature

### CODE REVIEW

**Review by sashaboi — CHANGES_REQUESTED** [review]
Code is very readable and review friendly, 
Liked the folder structure , it clearly shows how the data is flowing.
Looks good to merge!

**Review by sashaboi — APPROVED** [review]
Code is very readable and review friendly, 
Liked the folder structure , it clearly shows how the data is flowing.
Looks good to merge!

**Review by SukanyaSen530 — APPROVED** [review]

**Review by agrawalshanu708 — APPROVED** [review]
code structure is good,
Ui looks neat
can merge

**Review by xii-vi — APPROVED** [review]
really liked how you implemented the three-dot feature.
it gives a great UX.
Clean code and consistent design.
You can merge

**Pull request merged**
